//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class labEntities2 : DbContext
    {
        public labEntities2()
            : base("name=labEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<services_> services_ { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users_> users_ { get; set; }
        public virtual DbSet<Биоматериалы> Биоматериалы { get; set; }
        public virtual DbSet<Данные_о_работе_анализатора> Данные_о_работе_анализатора { get; set; }
        public virtual DbSet<Данные_о_страховых_компаниях> Данные_о_страховых_компаниях { get; set; }
        public virtual DbSet<Данные_пациентов> Данные_пациентов { get; set; }
        public virtual DbSet<Заказ> Заказ { get; set; }
        public virtual DbSet<История_входа> История_входа { get; set; }
        public virtual DbSet<Оказанная_услуга> Оказанная_услуга { get; set; }
        public virtual DbSet<Профессии> Профессии { get; set; }
        public virtual DbSet<Страховой_полис> Страховой_полис { get; set; }
        public virtual DbSet<Услуги_лаборатории> Услуги_лаборатории { get; set; }
        public virtual DbSet<Услуги_> Услуги_ { get; set; }
    }
}
