//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Данные_пациентов
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Данные_пациентов()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Код_пациента { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Серия_паспорта { get; set; }
        public string Номер_паспорта { get; set; }
        public string Телефон { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> Код_страхового_полиса { get; set; }
        public Nullable<int> Код_страховой_компании { get; set; }
    
        public virtual Данные_о_страховых_компаниях Данные_о_страховых_компаниях { get; set; }
        public virtual Страховой_полис Страховой_полис { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
