//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказ()
        {
            this.Услуги_лаборатории = new HashSet<Услуги_лаборатории>();
        }
    
        public int Код_заказа { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public string Статус_заказа { get; set; }
        public string Время_выполнения_заказа__в_днях_ { get; set; }
        public Nullable<int> Код_пациента { get; set; }
        public Nullable<int> Код_биоматериалов { get; set; }
    
        public virtual Биоматериалы Биоматериалы { get; set; }
        public virtual Данные_пациентов Данные_пациентов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги_лаборатории> Услуги_лаборатории { get; set; }
    }
}
