//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_входа
    {
        public int Код_входа { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
        public Nullable<System.DateTime> Дата_входа { get; set; }
        public string Состояние { get; set; }
    
        public virtual users_ users_ { get; set; }
    }
}
