//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оказанная_услуга
    {
        public int Код { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public Nullable<int> Код_сотрудника { get; set; }
        public Nullable<System.DateTime> Дата_оказания { get; set; }
        public Nullable<int> Код_анализатора { get; set; }
    
        public virtual users_ users_ { get; set; }
        public virtual Данные_о_работе_анализатора Данные_о_работе_анализатора { get; set; }
        public virtual Услуги_ Услуги_ { get; set; }
    }
}
