//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги_лаборатории
    {
        public int Код { get; set; }
        public string Наимениование { get; set; }
        public Nullable<double> Стоимость { get; set; }
        public Nullable<int> Код_услуги { get; set; }
        public Nullable<System.DateTime> Срок_выполнения { get; set; }
        public string Среднее_отклонение { get; set; }
        public Nullable<int> Код_заказа { get; set; }
    
        public virtual Заказ Заказ { get; set; }
        public virtual Услуги_ Услуги_ { get; set; }
    }
}
